// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3vqWd_ReJyeHVcqtGe7uPDN9Gw6IyjY',
    appId: '1:324991894056:web:3ded49b4babd1aa261eb1d',
    messagingSenderId: '324991894056',
    projectId: 'delloni',
    authDomain: 'delloni.firebaseapp.com',
    storageBucket: 'delloni.firebasestorage.app',
    measurementId: 'G-L3GET4YLJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ0mNpgPO5z2uI1qem3XMJbBypmySPkcM',
    appId: '1:324991894056:android:4b62f23aaff54a8461eb1d',
    messagingSenderId: '324991894056',
    projectId: 'delloni',
    storageBucket: 'delloni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVks3UoMiCfegHr-VvUo8skn8sn7Ca70',
    appId: '1:324991894056:ios:16a66088055e017561eb1d',
    messagingSenderId: '324991894056',
    projectId: 'delloni',
    storageBucket: 'delloni.firebasestorage.app',
    iosBundleId: 'com.app.delloni',
  );
}
